### ISSUE TITLE
Question about the Vim extension

### ISSUE THREAD

**Issue by Am1n3e** [nlx-404/.vscode#1]
First, thanks for sharing this!

Quick question, is there a specific reason why you are using the Vim extension instead of Neovim?  Does Nvim interfere with some of your changes?

Thanks,

**Comment by nlx-404** [comment]
Hi, honestly the only reason is I have never tried the neovim extension so I have no clue what it's like. I've always used the vim extension

**Comment by Am1n3e** [comment]
Thanks! 

FYI, I asked because using nvim extension, the UI fails to render properly sometimes (syntax highlighting)  and one need to refresh, not ideal.
